#!/usr/bin/env bash

PID_FILE="/var/run/my_process.pid"

start() {
  ./manage_my_process &
  echo $! > "$PID_FILE"
  echo "manage_my_process started"
}

stop() {
  kill "$(cat $PID_FILE)" 2>/dev/null
  rm -f "$PID_FILE"
  echo "manage_my_process stopped"
}

restart() {
  stop
  start
  echo "manage_my_process restarted"
}

case "$1" in
  start) start ;;
  stop) stop ;;
  restart) restart ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
